### ISSUE TITLE
Feature: Create the base recomendation calculations

### ISSUE THREAD

**Issue by deanraguso** [deanraguso/budgie#8]
## Context
The basic function of this application is to generate a budget for the user so that they can plan their spending and save accordingly.

As of yet, there is no such functionality. The first step to creating this functionality comes from a calculator that receives the inputs from the user and makes recommendations and goals from that data. 

##  Tasks
- [ ] Research a simple budgeting plan, and verify the inputs required are obtained in the current form.
- [ ] Create a service that generates the recommendations
  - [ ] It should have various tiers of strictness
  - [ ] Document exactly what type of data is required, and what time format it should be in
  - [ ] Test the formula on a known set of sample data
