### ISSUE TITLE
Feature: Upgrade the design to flow with the user

### ISSUE THREAD

**Issue by deanraguso** [deanraguso/budgie#9]
## Context
Currently, the design is more of a test for how it could be done, rather than a thought-out design that is pleasant to use. I want the site to flow through user input, bringing their focus to well-crafted segments, leading to a smooth input experience.

## Tasks
- [ ] Create a flow similar to the following.
  - [ ] User clicks start
  - [ ] User gets the income section focussed, and enters data, which is then validated
  - [ ] User gets progressed onto expenses, but just a particular topic (repeats until all information is input)
  - [ ] User gets asked to select how strict they want their spending to be, or if they have a savings goal and timeline for it.
  - [ ] The calculators run, and the users focus gets brought to the results section of the page

- [ ] Each input segment is clean, and the page is unpolluted by unneeded information.
- [ ] On the final page, the information is displayed in big but modern fonts, and in 3 distinct stages or steps (whichever looks best)
